app:
    resource: "@AppBundle/Controller/"
    type:     annotation
   
api:
    resource: .
    type:     api
    prefix:   /api # Optional

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc